// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB8THOfN7y6rmTimPCyIAmUlRPWKfeZCA',
    appId: '1:968481965741:web:f9bc6698abca34b5cce824',
    messagingSenderId: '968481965741',
    projectId: 'crud-d3431',
    authDomain: 'crud-d3431.firebaseapp.com',
    storageBucket: 'crud-d3431.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJh_xPB-d61Q3qknP8_p2k2PJMVhgGGFE',
    appId: '1:968481965741:android:84572b041a788c4acce824',
    messagingSenderId: '968481965741',
    projectId: 'crud-d3431',
    storageBucket: 'crud-d3431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSTNGkOFMA1k_FgUnS-3sUOPGQdmkpzU',
    appId: '1:968481965741:ios:24ff8f2cef547d82cce824',
    messagingSenderId: '968481965741',
    projectId: 'crud-d3431',
    storageBucket: 'crud-d3431.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSTNGkOFMA1k_FgUnS-3sUOPGQdmkpzU',
    appId: '1:968481965741:ios:55d0bbbed8b613b2cce824',
    messagingSenderId: '968481965741',
    projectId: 'crud-d3431',
    storageBucket: 'crud-d3431.appspot.com',
    iosBundleId: 'com.example.flutterCrud.RunnerTests',
  );
}
